### ISSUE TITLE
来自博客

### ISSUE THREAD

**Issue by Myway96** [wang-jinghui/MyCSDN_Blog#1]
https://blog.csdn.net/u014281392/article/details/77585419湿兄你好，能发下这篇博客里的数据和代码吗，才入坑好多不懂呀
1370190925@qq.com拜谢

**Comment by Chen8023** [comment]
大佬，求卷积神经网络CNN:Tensorflow实现(以及对卷积特征的可视化)的代码呀！地址是：https://blog.csdn.net/u014281392/article/details/74316028
给你 star, watch, fork了哦~
