### ISSUE TITLE
pyspark

### ISSUE THREAD

**Issue by LIZHZZ** [wang-jinghui/MyCSDN_Blog#4]
想借鉴一下pyspark实现的那个文本分类

**Comment by wang-jinghui** [comment]
这个我已经找不到了, 参考博客里面的片段就行, 是完整的

**Comment by wang-jinghui** [comment]
> 想借鉴一下pyspark实现的那个文本分类

https://github.com/wang-jinghui/MyCSDN_Blog/blob/master/PySpark/Pyspark_NLP_text_classification.ipynb 有了

**Comment by wang-jinghui** [comment]
https://github.com/wang-jinghui/MyCSDN_Blog/blob/master/PySpark/Pyspark_NLP_text_classification.ipynb
